Add files via upload
KenjIsanl/Lab-2 pull request #1
Opened 2024-10-25 20:20 UTC by KenjIsanl

![изображение_2024-10-25_232024539](https://github.com/user-attachments/assets/e7ea327c-3e03-4556-bba4-142a728c2f04)

2024-10-29 18:36 UTC, rmushkin requested changes
Небольшие правки. Пожалуйста, внесите.

2024-10-29 18:36 UTC, rmushkin commented on лаба 2/task_1.py
> +remains = money_capital + salary - spend
R. I. P.

2024-10-29 18:36 UTC, rmushkin commented on лаба 2/task_1.py
> +debt_free_counter = 1
Подождите, а если оста~~н~~тков не хватает прямо сразу?

2024-10-29 18:36 UTC, rmushkin commented on лаба 2/task_1.py
> +
PEP8

2024-10-29 18:36 UTC, rmushkin commented on лаба 2/task_2.py
> +
PEP8

2024-10-29 18:36 UTC, rmushkin commented on лаба 2/task_2.py
> +print(f"Подушка безопасности, чтобы протянуть 10 месяцев без долгов:", int(money_capital))
Ловушка с `int`: 3 рублей не хватит, чтобы купить гвоздь за 3 рубля 25 копеек. Надо округлять в большую сторону.

2024-10-31 12:26 UTC, rmushkin requested changes
У меня остался вопрос по поводу того, что будет, если остатков прямо сразу не хватит. И, забегая вперёд - а что будет, если их будет в точности столько, сколько хочется потратить?

2024-10-31 16:06 UTC, KenjIsanl commented
> У меня остался вопрос по поводу того, что будет, если остатков прямо сразу не хватит. И, забегая вперёд - а что будет, если их будет в точности столько, сколько хочется потратить?

Решила переработать код. Проверила при 3-ех случаях.

2024-11-01 17:14 UTC, rmushkin approved these changes
Принимается ✅

2024-11-01 17:15 UTC, rmushkin commented
Но вообще тут не обязательно отдельно рассматривать случаи) Можно просто всё в один, если с нестрогим равенством в условии цикла.

2024-11-01 17:17 UTC, merged